# Generated by Django 4.1.7 on 2023-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=64, verbose_name='카드이름')),
                ('cardtag', models.CharField(max_length=64, verbose_name='카드태그')),
                ('cardstatus', models.CharField(choices=[('처리중', '처리중'), ('배포됨', '배포됨')], default='처리중', max_length=64, verbose_name='카드상태')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='카드등록일시')),
                ('userid', models.CharField(max_length=64, verbose_name='회원아이디')),
            ],
            options={
                'verbose_name': '카드정보',
                'verbose_name_plural': '카드정보',
                'db_table': 'nevsp_cardinfo',
            },
        ),
    ]
