# Generated by Django 4.1.7 on 2023-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evmain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiCount', models.IntegerField(verbose_name='금일 가입자')),
                ('regiTotal', models.IntegerField(verbose_name='누적 가입자')),
                ('useCharger', models.IntegerField(verbose_name='사용중인 충전기')),
                ('totalCharger', models.IntegerField(verbose_name='총 충전기')),
                ('totalenergy', models.CharField(max_length=128, verbose_name='금일 누적 충전량')),
                ('totalamount', models.CharField(default=0, max_length=128, null=True, verbose_name='금일 충전금액')),
                ('eventcurrent', models.CharField(max_length=128, verbose_name='진행중인 이벤트 현황')),
                ('systemday', models.DateTimeField(null=True, verbose_name='당일날짜')),
            ],
            options={
                'verbose_name': '메인화면',
                'verbose_name_plural': '메인',
                'db_table': 'nevsp_evmain',
            },
        ),
    ]
